name: Build and Test

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set env vars
      run: |
        cp .env.template .env
          sed -i "s|%URL%|${{ secrets.URL }}|g" .env
          sed -i "s|%SECRETUI%|${{ secrets.SECRETUI }}|g" .env

          sed -i "s|%FBAPIKEY%|${{ secrets.FBAPIKEY }}|g" .env
          sed -i "s|%FBAUTHDOMAIN%|${{ secrets.FBAUTHDOMAIN }}|g" .env
          sed -i "s|%FBPROJECTID%|${{ secrets.FBPROJECTID }}|g" .env
          sed -i "s|%FBSTORAGE%|${{ secrets.FBSTORAGE }}|g" .env
          sed -i "s|%FBMESSAGINGSENDERID%|${{ secrets.FBMESSAGINGSENDERID }}|g" .env
          sed -i "s|%FBAPPID%|${{ secrets.FBAPPID }}|g" .env
          sed -i "s|%FBMEASUREMENTID%|${{ secrets.FBMEASUREMENTID }}|g" .env

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - run: npm run build

  test:
    name: Test Project & Run SonarCloud Scan
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - name: Run jest Tests
      run: npm run test
    - name: Generate Coverage Report
      run: npx jest --coverage
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  release:
    name: Run Semantic-Release
    needs: [build, test]
    runs-on: ubuntu-22.04
    permissions:
      contents: write 
      issues: write
      pull-requests: write 
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        token: ${{ secrets.GH_TOKEN }}
    - name: Install all dependencies
      run: npm ci
    - name: Run Semantic-Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npx semantic-release
     
  


  
