name: Build and Test

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - run: npm run build

  test:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - name: Run jest Tests
      run: npm run test
    - name: Generate Coverage Report
      run: npx jest --coverage
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  release:
    needs: [build, test]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install all dependencies
      run: npm ci
    - name: Run Semantic-Release
      run: npx semantic-release
      env: 
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
  


    
